### ISSUE TITLE
 Could not create quote as your guild has reached the max of 10000 quotes message appears on .q

### ISSUE THREAD

**Issue by RansomTime** [reddit-diabetes/diabot-discord#198]
**Describe the bug**
Recalling a quote creates the above message on recalling a quote

**To Reproduce**
use the .q command (or any other command that uses checkRestrictions without checking the quote limit)

**Expected behavior**
Quote is recalled because this is not a creation event

**Screenshots**
![image](https://github.com/discord-diabetes/diabot/assets/47819665/7d6ac00f-a3b2-4c4a-88e6-6adc008bc0dc)

**Additional context**
Beleive this is caused by this line https://github.com/discord-diabetes/diabot/blob/84199ddc5aaa107e09a85a8719961c2d5d427b6b/bot/src/main/java/com/dongtronic/diabot/platforms/discord/listeners/QuoteListener.kt#L99

**Comment by cascer1** [comment]
Thanks for your report. Indeed the bot should still show existing quotes even if the limit was reached.
